### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by Borbosch** [EdonGashi/gamepad-mapper#1]
I'm trying to use this with my Windows 10 Machine. On Launch of the Application nothing happens, expcept the creation of a Logfile with the following content:

Warning: Value '1.3' is invalid or out of range for key 'mouse.acceleration' at config.txt:17. Default value is assigned.
Warning: Value '1.5' is invalid or out of range for key 'scroll.acceleration' at config.txt:23. Default value is assigned.

**Comment by edongashi** [comment]
Hmm, that's a weird behavior with the out of range values, but the app should still start. Can you check task manager to see if the process is alive?

I will investigate, and add some logging in case of crashes. Thanks for reporting this issue, I'll keep you updated.

**Comment by Borbosch** [comment]
In the task manager the app is only visible for like 2 seconds, after that it disappears. Do i have to install any additional software? .net framework or something like that?

**Comment by edongashi** [comment]
.net framework yes. But considering the log file is generated it means that the application is running initially, but its crashing for some reason.

90% its something wrong with the way config files are read. Is your computer language different from english? I have to make sure that localization does not affect the way numbers are read from config.

Thanks for your help, we will figure it out quickly. Once i get access to my pc I will be able to investigate.

**Comment by Borbosch** [comment]
My Windows is set to German. Hope that helps. If you need something Else to debug, just let me know.

**Comment by edongashi** [comment]
When computer language is different, it expects numbers differently, for example instead of `1.3` it may expect `1,3`. I published [GamepadMapper 1.0.0 Alpha 2](https://github.com/EdonGashi/gamepad-mapper/releases) release that fixes this. Could you please check it out and see if it starts now?

In case of a terminating error it will now log the error to the logfile. If that happens please paste it here so we can pinpoint the issue.

**Comment by edongashi** [comment]
Note: all you need to do is run the .exe file and leave it running. Try moving your left stick to see if there is any mouse movement.

Pressing LB it will show the radial menu. I'm thinking of porting this to a console app for people that don't care about the graphical UI.

config.txt holds your configuration (profiles, mappings, fps, deadzones, etc). First try running it with default config and then you can tweak it to your liking. Hope this works. Feedback is appreciated. Thanks!

**Comment by Borbosch** [comment]
WIth the new version i get the following error in the log. I seems as if it tries to load remote ressources. That seems strange.

`=== Critical failure ===
System.IO.FileLoadException: Die Datei oder Assembly "file:///C:\Users\patri\Documents\My Games\Emulatoren\Gamepadmapper\Ninject.Extensions.Factory.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)
Dateiname: "file:///C:\Users\patri\Documents\My Games\Emulatoren\Gamepadmapper\Ninject.Extensions.Factory.dll" ---> System.NotSupportedException: Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=155569".

   bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   bei System.Reflection.Assembly.LoadFrom(String assemblyFile)
   bei Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   bei Ninject.Modules.AssemblyNameRetriever.AssemblyChecker.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   bei Ninject.Modules.AssemblyNameRetriever.GetAssemblyNames(IEnumerable`1 filenames, Predicate`1 filter)
   bei Ninject.Modules.CompiledModuleLoaderPlugin.LoadModules(IEnumerable`1 filenames)
   bei Ninject.Modules.ModuleLoader.LoadModules(IEnumerable`1 patterns)
   bei Ninject.KernelBase..ctor(IComponentContainer components, INinjectSettings settings, INinjectModule[] modules)
   bei GamepadMapper.Wpf.App.OnAppStartup(Object sender, StartupEventArgs e)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.Exce`

**Comment by edongashi** [comment]
I see the problem. It's blocking .dll files for security reasons.

Can you try this with the .dll files? (right click -> properties)

![](https://i.stack.imgur.com/V4Lco.png)

Otherwise download alpha 3 release, which will fix it.

**Comment by Borbosch** [comment]
Wow thanks! The hint with the unblock did it and the new alpha 3 works as well. Now for some serious testing! ;-)

**Comment by edongashi** [comment]
Thank you for helping out! Looking forward to more feedback.
