### ISSUE TITLE
Can't use VK_OEM_PLUS or VK_OEM_MINUS

### ISSUE THREAD

**Issue by MrSwiss** [EdonGashi/gamepad-mapper#2]
I would like to add Ctrl+plus/minus for zoom in/out. But I can't figure what setting I should use.
I tried VK_OEM_PLUS, VK_PLUS, PLUS, but non of these works.

Thanks for amazing opensource software.

**Comment by MrSwiss** [comment]
I found it. >> OEM_MINUS

**Comment by edongashi** [comment]
Hi, thanks! You can find the complete list of virtual keys here: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
